# Generated by Django 3.2.7 on 2021-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_people_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='data_nasc',
            field=models.DateField(),
        ),
    ]
