# Generated by Django 3.2.7 on 2021-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_people_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1),
        ),
    ]
