# Generated by Django 3.2.7 on 2021-10-05 22:53

from django.db import migrations
from django.utils.text import slugify


def slugify_cpf(apps, schema_editor):
    People = apps.get_model('core', 'People')
    for people in People.objects.all():
        people.slug = slugify(people.cpf)
        people.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_people_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_cpf),
    ]
