# Generated by Django 3.2.7 on 2021-10-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211005_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
