# Generated by Django 3.2.7 on 2021-10-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_people_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='slug',
        ),
    ]
