# Generated by Django 3.2.7 on 2021-10-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_people_signo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='signo',
        ),
    ]
