# Generated by Django 3.2.7 on 2021-10-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_skill', models.CharField(default='', max_length=100)),
                ('porcentagem', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
