# Generated by Django 3.2.8 on 2021-10-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adressess_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorios',
            name='observacao',
            field=models.CharField(max_length=500),
        ),
    ]
