# Generated by Django 3.2.8 on 2021-10-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cartorios_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorios',
            name='area_de_abrangencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='atribuicoes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='comarca',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='entrancia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='horario_de_funcionamento',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='nome_oficial',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cartorios',
            name='ultima_atualizacao',
            field=models.CharField(max_length=500),
        ),
    ]
