# Generated by Django 3.2.8 on 2021-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211020_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorios',
            name='atribuicoes',
            field=models.CharField(max_length=600),
        ),
    ]
