# Generated by Django 3.2.8 on 2021-10-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cartorios_area_de_abrangencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorios',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=301, null=True),
        ),
    ]
