# Generated by Django 3.2.8 on 2021-10-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contactinformation_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorios',
            name='uf',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
